apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: CLO835
  namespace: final
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-binding
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
roleRef:
  kind: Role
  name: CLO835
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask-app
        image: 975050319979.dkr.ecr.us-east-1.amazonaws.com/clo835-final-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: BG_IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BG_IMAGE_URL
        - name: HEADER_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HEADER_NAME
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AWS_DEFAULT_REGION
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 81